"use client";
import {useState} from 'react';
import {Leaf, BookOpen, Box, ClipboardCheck, Sprout, ShieldCheck, Users, GraduationCap, Eye, EyeOff, LoaderCircle} from 'lucide-react';
import {RadioGroup, RadioGroupItem} from '@/components/ui/radio-group';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export function Brand(){return <a href="/" className="brand"><span className="brand-mark"><Sprout size={25}/></span><span>智伴成长<small>LABOR & GROWTH</small></span></a>}
export default function Landing(){
 const [role,setRole]=useState('teacher'),[register,setRegister]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false),[forgot,setForgot]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const d=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch('/api/'+(register?'register':'login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,role})});const j:any=await r.json();if(!r.ok)throw Error(j.error);location.href='/portal';}catch(e){setError(e instanceof Error?e.message:'暂时无法登录，请稍后重试')}finally{setBusy(false)}}
 const modules=[{Icon:BookOpen,n:'01',title:'智能课程资源',text:'从备课到课堂，连接课标与实践。按学段与主题生成教案、任务单和评价量表。',tag:'备课更轻松'},{Icon:Box,n:'02',title:'虚拟劳动实训',text:'先在虚拟场景里练习，再动手实践。分步引导、安全提醒，记录每一次进步。',tag:'在实践中学习'},{Icon:ClipboardCheck,n:'03',title:'劳动成果评价',text:'记录劳动过程与成果，辅助初审与教师复核协同，让每一份努力得到回应。',tag:'让评价有依据'},{Icon:Sprout,n:'04',title:'劳动成长档案',text:'汇集任务、实训与教师评语，形成可以回顾、可以导出的个人成长记录。',tag:'看见每一步成长'}];
 return <><header className="landing-header"><div className="nav-wrap"><Brand/><nav><a href="#home">首页</a><a href="#modules">核心模块</a><a href="#platform">平台介绍</a><a href="#team">团队</a></nav><a className="nav-enter" href="#login">进入平台</a></div></header><main>
 <section id="home" className="hero"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><span/>让劳动教育，发生在每一天</div><h1>在劳动中探索<br/>在实践中<span>成长<svg viewBox="0 0 190 14"><path d="M4 9 Q90 -2 184 7" fill="none" stroke="#a7cb61" strokeWidth="7" strokeLinecap="round"/></svg></span></h1><p className="hero-intro">虚实融合 AI 劳动教育实训评价平台</p><p className="hero-desc">连接课堂、家庭与真实生活。让备课更轻松，让实践更安全，让每一次劳动都有迹可循。</p><div className="labor-tags"><span><Leaf size={15}/>日常生活劳动</span><span><Sprout size={15}/>生产劳动</span><span><Users size={15}/>服务性劳动</span></div><div className="hero-visual"><img src="/learning.png" alt="种植、收纳与劳动学习空间" onError={e=>{e.currentTarget.style.display='none'}}/><div className="visual-caption"><span>LEARN BY DOING</span><strong>从一次动手，开始一段成长。</strong></div></div></div>
 <div id="login" className="login-card"><div className="login-top"><span className="login-icon"><GraduationCap size={26}/></span><span className="edition">劳动教育 · 三端协同</span></div><h2>{register?'开启成长之旅':'欢迎来到智伴成长'}</h2><p className="muted">{register?'创建账号，开始你的劳动学习与教学。':'选择你的身份，进入专属工作空间。'}</p><form onSubmit={submit}><RadioGroup className="role-picker" value={role} onValueChange={setRole}>{[['teacher','教师'],['student','学生'],['parent','家长']].map(([v,t])=><label key={v} className={role===v?'chosen':''}><RadioGroupItem value={v}/>{t}</label>)}</RadioGroup><label className="field">账号<input name="username" autoComplete="username" placeholder="请输入账号" required minLength={3} maxLength={40}/></label>{register&&<label className="field">姓名<input name="real_name" placeholder="请输入你的姓名" required maxLength={30}/></label>}<label className="field">密码<div className="password"><input name="password" autoComplete={register?'new-password':'current-password'} type={show?'text':'password'} placeholder={register?'至少 8 位字符':'请输入密码'} required minLength={register?8:1}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'隐藏密码':'显示密码'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{register&&<><label className="field">确认密码<input name="confirm" type="password" required placeholder="再次输入密码"/></label>{role==='student'&&<label className="field">班级邀请码（可选）<input name="join_code" placeholder="由任课教师提供，留空加入个人测试班级"/></label>}{role==='parent'&&<label className="field">学生绑定码<input name="binding_code" required placeholder="由任课教师提供"/></label>}</>}<div className="login-help"><span>{role==='teacher'?'为每一次成长，做好准备':role==='student'?'把知识变成动手的能力':'陪伴孩子，在劳动中长大'}</span>{!register&&<button type="button" onClick={()=>setForgot(true)}>忘记密码？</button>}</div>{error&&<p className="error" role="alert">{error}</p>}<button className="btn primary login-button" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:null}{busy?'正在处理…':register?'创建账号':'登录平台'}</button><div className="register-link">{register?'已有账号？':'还没有账号？'}<button type="button" onClick={()=>{setRegister(!register);setError('')}}>{register?'返回登录':'立即注册'}</button></div></form><div className="demo-entry"><span>先看看平台？</span>{[['teacher','教师'],['student','学生'],['parent','家长']].map(([r,t])=><button key={r} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const response=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:r})});const j:any=await response.json();if(!response.ok)throw Error(j.error);location.href='/portal'}catch(e){setError((e as Error).message);setBusy(false)}}}>{t}体验</button>)}</div><div className="login-foot"><ShieldCheck size={16}/>教师、学生、家长数据按身份隔离</div></div></div></section>
 <section id="modules" className="landing-section"><div className="section-heading"><div><div className="eyebrow">一条完整的劳动学习路径</div><h2>从课程准备，到成长记录</h2></div><p>四大核心模块，连接教、学、练、评。</p></div><div className="module-grid">{modules.map(({Icon,n,title,text,tag})=><article className="module-card" key={n}><div className="module-top"><span><Icon size={26}/></span><small>{n}</small></div><h3>{title}</h3><p>{text}</p><div className="module-tag">{tag}</div></article>)}</div></section>
 <section id="platform" className="platform-section"><div className="landing-section"><div className="section-heading"><div><div className="eyebrow">学校 · 学生 · 家庭</div><h2>各司其职，也彼此连接</h2></div><p>一份任务，让课堂与生活自然衔接。</p></div><div className="role-grid"><article><GraduationCap/><small>FOR TEACHERS</small><h3>教学有支撑</h3><p>生成课程资源、发布劳动任务、复核成果，管理班级并导出劳动台账。</p></article><article><Sprout/><small>FOR STUDENTS</small><h3>实践有方向</h3><p>探索劳动知识、练习操作流程、提交真实成果，积累自己的成长档案。</p></article><article><Users/><small>FOR PARENTS</small><h3>陪伴有反馈</h3><p>关注孩子的任务和教师评语，回顾成长记录，把劳动习惯带入日常生活。</p></article></div><div className="advantage"><span><ShieldCheck/>三端权限隔离</span><span><Box/>网页 3D 实训</span><span><ClipboardCheck/>辅助初审与教师复核</span><span><BookOpen/>成长记录自动归档</span></div></div></section>
 <section id="team" className="landing-section team-section"><div><div className="eyebrow">关于项目</div><h2>用技术，陪伴劳动教育</h2><p>智伴成长聚焦中小学劳动教学，把课程资源、虚拟练习、成果评价与成长记录连接起来。</p></div><div className="team-note"><Leaf size={28}/><strong>智伴成长项目组</strong><span>课程设计 · 平台研发 · 实训设计</span></div></section></main><footer className="landing-footer"><Brand/><span>让每一次劳动，都成为成长的养分。</span><small>© 2026 智伴成长</small></footer><Dialog open={forgot} onOpenChange={setForgot}><DialogContent><DialogHeader><DialogTitle>找回账号密码</DialogTitle><DialogDescription>请联系你的任课教师或平台负责人核实身份并处理账号问题。当前版本暂未接入短信或邮件找回。</DialogDescription></DialogHeader></DialogContent></Dialog></>
}
